### ISSUE TITLE
项目的最后更新时间不准确

### ISSUE THREAD

**Issue by lovue** [LeslieLeung/opensource-lighthouse#12]
很多项目的最后更新时间都不准确，而且差得比较离谱，不知道是怎么获取的。
比如：https://github.com/AlloyTeam/Mars

**Comment by LeslieLeung** [comment]
取的是项目的 `updated_at`字段，见 [API](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories)，只要项目属性有更新就会变动。你理解的「最后更新时间」可能是指最后一次 commit 的时间，对应有 `pushed_at` 字段。

我不确定哪一个更加符合大家理解的「最后更新时间」，我后续会把「最后一次提交时间」也加上。
